### ISSUE TITLE
Just a suggestion

### ISSUE THREAD

**Issue by rcrooks** [riyuzenn/vscode#1] opened 2022-09-10 13:24 UTC
@riyuzenn This isn't really an issue with your beautiful theme, just a somewhat selfish suggestion: I frequently work in large repositories with hundreds or thousands of files. Highlighting in the sidebar the one that's currently open in the editor a little more prominently would be a real boon.

**Comment by riyuzenn** [comment] 2022-09-13 04:29
Hey there! First of all, thanks for opening an issue for improvements. Second of all, I'm sorry for the delayed response. I've already changed the editor and sidebar scrollbar colors, as well as the colors used for error linting. I'll leave this matter open for more improvement. The replacement version will then be made available through the vscode extension after the issue is closed.  Again, thanks and have a great day!

**Comment by rcrooks** [comment] 2022-09-13 15:29
Thanks and no worries, it's quite usable and a pleasure to use as is.

**Comment by riyuzenn** [comment] 2022-09-13 15:58
v0.0.3 is up now! closing the issue, thank you again.

**Closed as completed by riyuzenn** 2022-09-13 15:58 UTC
Labels: enhancement

**Comment by rcrooks** [comment] 2022-09-13 18:08
Awesome! Thanks so much!
